services:
  db:
    image: mysql:latest
    container_name: db-container
    restart: always
    environment:
      MYSQL_DATABASE: 'MUSICFM'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
    command: --secure-file-priv="" --local-infile=1
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      interval: 5s
      retries: 10
  app:
    depends_on:
      db:
        condition: service_healthy
    container_name: app-container
    build: 
      context: ./server
    ports:
      - 8000:5000
    volumes:
      - ./server:/app
  client:
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    container_name: client-container
    volumes:
      - ./client:/app
    build:
      context: ./client
    ports:
      - 3000:3000
