services:
  db:
    image: mysql:latest
    container_name: db-container
    restart: always
    environment:
      MYSQL_DATABASE: 'MUSICFM'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3000:3306'
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
      - ./data:/data
    command: --secure-file-priv="" --local-infile=1
  app:
    container_name: app-container
    build: .
    ports:
      - 8000:5000
